Meteor.subscribe("tableLocations");
Meteor.subscribe('units');
Meteor.subscribe('categories');
Meteor.subscribe('materialCategories');
Meteor.subscribe('images');
Meteor.subscribe('currencies');
Meteor.subscribe('company');
Meteor.subscribe('exchangeRates');
Meteor.subscribe("tables");
